let tags = [
    {
        "songName": "potadhu-pathala.txt",
        "tags": [
            "Middle Eastern music",
            "Rock and roll",
            "Rock music",
            "Ska",
            "colloquial",
            "dance",
            "language",
            "party",
            "revelry",
            "socialising",
            "speech",
            "upbeat"
        ]
    },
    {
        "songName": "aararo-song-lyrics.txt",
        "tags": [
            "Acoustic guitar",
            "Guitar",
            "Lullaby",
            "Plucked string instrument",
            "Strum",
            "admiration",
            "affection",
            "anticipation",
            "appreciation",
            "contemplative",
            "destiny",
            "determination",
            "empowerment",
            "inspiration",
            "introspective",
            "language",
            "leadership",
            "metaphorical",
            "metaphysical",
            "personification",
            "philosophical",
            "philosophy",
            "poetic",
            "reflection",
            "symbolic",
            "validation"
        ]
    },
    {
        "songName": "aazha-kannal-song-lyrics.txt",
        "tags": [
            "appreciation",
            "beauty",
            "communication",
            "cultural",
            "diversity",
            "expression",
            "identity",
            "imagery",
            "language",
            "perception",
            "sensory"
        ]
    },
    {
        "songName": "adada-mazhaida-song-lyrics.txt",
        "tags": [
            "Flamenco",
            "Folk music",
            "Guitar",
            "Plucked string instrument",
            "Traditional music",
            "emotion",
            "expression",
            "expressive",
            "imagery",
            "language",
            "longing",
            "love",
            "lyricism",
            "nature",
            "perception",
            "poetic",
            "rain",
            "romantic",
            "sensory",
            "surrealism",
            "transcendence",
            "transience"
        ]
    },
    {
        "songName": "adiye-adiye-song-lyrics.txt",
        "tags": [
            "anticipation",
            "contemplative",
            "determination",
            "emotion",
            "existential",
            "expression",
            "expressive",
            "imagery",
            "individualism",
            "introspective",
            "journey",
            "language",
            "materialism",
            "metaphysical",
            "morality",
            "mystery",
            "nature",
            "perception",
            "personification",
            "poetic",
            "reflection",
            "sensory",
            "spiritual",
            "symbolic",
            "transcendence",
            "transcendentalism",
            "transience",
            "uncertainty",
            "validation"
        ]
    },
    {
        "songName": "aila-aila-song-lyrics.txt",
        "tags": [
            "Mallet percussion",
            "Opera",
            "Percussion",
            "admiration",
            "affection",
            "appreciation",
            "celebration",
            "dance",
            "dancing",
            "energetic",
            "joyful",
            "joyous",
            "love",
            "metaphor",
            "metaphorical",
            "playful",
            "romantic"
        ]
    },
    {
        "songName": "anbe-anbe-kollathey-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "art",
            "beauty",
            "care",
            "contentment",
            "determination",
            "devotion",
            "gentleness",
            "imaginative",
            "infatuation",
            "inspiration",
            "love",
            "nature",
            "oneness",
            "painting",
            "personification",
            "playfulness",
            "plea",
            "protection",
            "romance",
            "sculpture"
        ]
    },
    {
        "songName": "anbin-vaasale-song-lyrics.txt",
        "tags": [
            "devotion",
            "dissolution",
            "divine",
            "elements",
            "enlightenment",
            "gentleness",
            "impermanence",
            "love",
            "metaphysical",
            "nature",
            "oneness",
            "personification",
            "reincarnation",
            "separation",
            "soul",
            "spiritual",
            "surrender",
            "transcendence",
            "transcendentalism",
            "transience",
            "unity",
            "worship"
        ]
    },
    {
        "songName": "Andhi-mazhai-megam-song-lyrics.txt",
        "tags": [
            "auspicious",
            "celebration",
            "community",
            "cultural",
            "culture",
            "folklore",
            "gratitude",
            "harvest",
            "joy",
            "pride",
            "rain",
            "street",
            "traditions",
            "unity"
        ]
    },
    {
        "songName": "annachi-ammachi-song-lyrics.txt",
        "tags": [
            "Folk music",
            "Percussion",
            "accountability",
            "affection",
            "campaigning",
            "creation",
            "culture",
            "determination",
            "election",
            "energy",
            "excitement",
            "exploitation",
            "identity",
            "mobilisation",
            "motivation",
            "personification",
            "political",
            "power",
            "propaganda",
            "reconciliation",
            "reflection",
            "separation",
            "transformation",
            "unity",
            "victory"
        ]
    },
    {
        "songName": "annanoda-pattu-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Tabla",
            "anticipation",
            "appreciation",
            "brotherhood",
            "celebration",
            "cultural",
            "culture",
            "determination",
            "encouragement",
            "frustration",
            "hope",
            "knowledge",
            "motivation",
            "optimism",
            "perception",
            "personification",
            "prosperity",
            "roots",
            "traditions",
            "transformation",
            "transience",
            "understanding",
            "validation"
        ]
    },
    {
        "songName": "appadi-podu-song-lyrics.txt",
        "tags": [
            "Folk music",
            "Jazz",
            "Percussion",
            "Smash, crash",
            "Whack, thwack",
            "affection",
            "attraction",
            "dance",
            "dancing",
            "desire",
            "desperation",
            "duality",
            "energy",
            "flirting",
            "frustration",
            "gentleness",
            "infatuation",
            "intimacy",
            "love",
            "personification",
            "playfulness",
            "romance",
            "seduction",
            "temptation",
            "transience",
            "yearning"
        ]
    },
    {
        "songName": "arima-arima-song-lyrics.txt",
        "tags": [
            "Brass instrument",
            "Rock and roll",
            "Rock music",
            "Trumpet",
            "boasting",
            "desire",
            "innovation",
            "power",
            "pride",
            "robotic",
            "robots",
            "technology"
        ]
    },
    {
        "songName": "arjunaru-villu-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Rock music",
            "Strum",
            "affection",
            "battle",
            "bravery",
            "courage",
            "determination",
            "heroism",
            "inspiration",
            "language",
            "motivation",
            "transformation",
            "triumph",
            "uplifting",
            "victory",
            "war"
        ]
    },
    {
        "songName": "asku-laska-song-lyrics.txt",
        "tags": [
            "Jingle bell",
            "Rock and roll",
            "Rock music",
            "Tender music",
            "admiration",
            "affection",
            "appreciation",
            "desire",
            "devotion",
            "emotion",
            "expression",
            "expressive",
            "longing",
            "love",
            "poetic",
            "poetry",
            "romance",
            "transience"
        ]
    },
    {
        "songName": "athinthom-song-lyrics.txt",
        "tags": [
            "Bass drum",
            "Drum",
            "Middle Eastern music",
            "Percussion",
            "bhakti",
            "celebration",
            "cultural",
            "culture",
            "dance",
            "dancing",
            "devotion",
            "enlightenment",
            "happiness",
            "joyful",
            "joyous",
            "language",
            "oneness",
            "poetic",
            "poetry",
            "rhythmic",
            "spiritual",
            "traditions",
            "transcendence",
            "transcendentalism"
        ]
    },
    {
        "songName": "boom-boom-robo-da-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Smash, crash",
            "Whack, thwack",
            "admiration",
            "affection",
            "appreciation",
            "creation",
            "creative",
            "creativity",
            "energy",
            "futuristic",
            "innovation",
            "robotic",
            "robots",
            "science",
            "technology",
            "transformation",
            "wonder"
        ]
    },
    {
        "songName": "chithirai-nela-song-lyrics.txt",
        "tags": [
            "creation",
            "droplets",
            "earth",
            "epic",
            "ether",
            "flower",
            "honey",
            "innovation",
            "lamp",
            "laughter",
            "light",
            "mobilisation",
            "moon",
            "nations",
            "personification",
            "river",
            "scenes",
            "seed",
            "separation",
            "sky",
            "transformation",
            "treasure",
            "trees",
            "wisdom"
        ]
    },
    {
        "songName": "columbus-columbus-song-lyrics.txt",
        "tags": [
            "Tap",
            "celebration",
            "childhood",
            "freedom",
            "imaginative",
            "inspiration",
            "meditation",
            "metaphorical",
            "metaphysical",
            "nature",
            "philosophical",
            "philosophy",
            "poetic",
            "poetry",
            "relaxation",
            "surrealism",
            "travel",
            "vacation",
            "wanderlust"
        ]
    },
    {
        "songName": "devuda-devuda-song-lyrics.txt",
        "tags": [
            "Brass instrument",
            "appreciation",
            "belief",
            "cultural",
            "culture",
            "encouragement",
            "faith",
            "hope",
            "humility",
            "inspiration",
            "metaphorical",
            "metaphysical",
            "motivation",
            "optimism",
            "perseverance",
            "persistence",
            "philosophical",
            "philosophy",
            "spiritual",
            "traditions",
            "unity",
            "uplifting",
            "values"
        ]
    },
    {
        "songName": "edhirthu-nil-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Pop music",
            "Rock and roll",
            "Rock music",
            "Roll",
            "accountability",
            "affection",
            "anticipation",
            "courage",
            "determination",
            "humility",
            "inspiration",
            "motivation",
            "perseverance",
            "persistence",
            "personification",
            "positive",
            "positivity",
            "reconciliation",
            "reflection",
            "resilience",
            "separation",
            "success",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "elay-keechaan-song-lyrics.txt",
        "tags": [
            "cultural",
            "culture",
            "fishing",
            "laughter",
            "longing",
            "love",
            "memories",
            "nostalgia",
            "repetition",
            "sea"
        ]
    },
    {
        "songName": "en-frienda-pola-song-lyrics.txt",
        "tags": [
            "Rock music",
            "Tap",
            "Tender music",
            "Thump, thud",
            "companion",
            "companionship",
            "creation",
            "determination",
            "dissolution",
            "emotion",
            "friendship",
            "longing",
            "loss",
            "loyalty",
            "memories",
            "nostalgia",
            "personification",
            "reconciliation",
            "relationship",
            "sensations",
            "separation",
            "sorrow",
            "sorrowful",
            "support",
            "transformation",
            "trust",
            "validation"
        ]
    },
    {
        "songName": "En-jannalil-therivadhu-song-lyrics.txt",
        "tags": [
            "anticipation",
            "beauty",
            "contemplative",
            "destiny",
            "determination",
            "enlightenment",
            "hope",
            "introspective",
            "longing",
            "loss",
            "melancholic",
            "mystery",
            "nature",
            "oneness",
            "personification",
            "questioning",
            "reflection",
            "spiritual",
            "symbolic",
            "transcendence",
            "transcendentalism",
            "validation",
            "yearning"
        ]
    },
    {
        "songName": "en-kaadhal-solla-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Folk music",
            "Middle Eastern music",
            "accountability",
            "admiration",
            "affection",
            "appreciation",
            "commitment",
            "contentment",
            "desire",
            "desperation",
            "determination",
            "devotion",
            "frustration",
            "honesty",
            "inevitability",
            "infatuation",
            "intimacy",
            "longing",
            "love",
            "personification",
            "romantic",
            "trust",
            "vulnerability",
            "yearning"
        ]
    },
    {
        "songName": "enake-enaka-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "Rock music",
            "admiration",
            "affection",
            "beauty",
            "contentment",
            "desire",
            "determination",
            "happiness",
            "infatuation",
            "longing",
            "love",
            "nature",
            "personification",
            "poetic",
            "poetry",
            "romance",
            "travel"
        ]
    },
    {
        "songName": "endhan-kan-munne-song-lyrics.txt",
        "tags": [
            "communication",
            "consent",
            "contemplative",
            "determination",
            "difficulty",
            "emotion",
            "heartbreak",
            "inevitability",
            "introspective",
            "longing",
            "motivation",
            "pain",
            "pensive",
            "permission",
            "personification",
            "reflective",
            "separation",
            "transformation",
            "validation",
            "vulnerability"
        ]
    },
    {
        "songName": "ennodu-nee-irundhal-song-lyrics.txt",
        "tags": [
            "Country",
            "Guitar",
            "Plucked string instrument",
            "Tender music",
            "attachment",
            "devotion",
            "expressive",
            "fantasy",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "poetic",
            "poetry",
            "sacrifice",
            "separation",
            "yearning"
        ]
    },
    {
        "songName": "heartile-battery-song-lyrics.txt",
        "tags": [
            "absurd",
            "absurdity",
            "creative",
            "creativity",
            "disjointed",
            "humorous",
            "imaginative",
            "irrational",
            "lighthearted",
            "nonsensical",
            "playful",
            "poetic",
            "poetry",
            "positive",
            "positivity",
            "unconventional",
            "wordplay"
        ]
    },
    {
        "songName": "honey-honey-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "absurd",
            "absurdity",
            "ambiguous",
            "chaotic",
            "creative",
            "flirtatious",
            "humorous",
            "imaginative",
            "nonsensical",
            "playful",
            "poetic",
            "poetry",
            "romantic",
            "seductive",
            "whimsical"
        ]
    },
    {
        "songName": "Idhudhaanaa-idhudhaanaa-song-lyrics.txt",
        "tags": [
            "affection",
            "anticipation",
            "determination",
            "infatuation",
            "intoxication",
            "life",
            "mobilisation",
            "personification",
            "separation",
            "togetherness"
        ]
    },
    {
        "songName": "irukana-idupirukana-song-lyrics.txt",
        "tags": [
            "Clip-clop",
            "admiration",
            "affection",
            "beauty",
            "creation",
            "desire",
            "duality",
            "flirting",
            "intimacy",
            "language",
            "love",
            "obsession",
            "personification",
            "pleasure",
            "romantic"
        ]
    },
    {
        "songName": "irumbile-oru-irudhaiyam-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "dance",
            "dancing",
            "desire",
            "futuristic",
            "hypnotic",
            "innovation",
            "love",
            "pop",
            "robotic",
            "robots",
            "romantic",
            "seductive",
            "technology"
        ]
    },
    {
        "songName": "kaal-mulaitha-poove-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "art",
            "beauty",
            "dance",
            "dancing",
            "desire",
            "duality",
            "fire",
            "love",
            "melting",
            "moon",
            "nature",
            "river",
            "romance",
            "singing"
        ]
    },
    {
        "songName": "kaalam-en-kadhali-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "Rock music",
            "Sound effect",
            "beauty",
            "change",
            "clock",
            "death",
            "energy",
            "fear",
            "finger",
            "girlfriend",
            "god",
            "heart",
            "heaven",
            "joy",
            "knowledge",
            "love",
            "magic",
            "moon",
            "power",
            "reward",
            "space",
            "sun",
            "tantra",
            "time",
            "understanding",
            "universe"
        ]
    },
    {
        "songName": "kaatrin-mozhi-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Guitar",
            "Harpsichord",
            "Mallet percussion",
            "Percussion",
            "Plucked string instrument",
            "Sitar",
            "colour",
            "communication",
            "connection",
            "desire",
            "directionless",
            "eyes",
            "fishes",
            "flower",
            "god",
            "heart",
            "love",
            "nature",
            "nonverbal",
            "personification",
            "shame",
            "silence",
            "smell",
            "sound",
            "speech",
            "tears",
            "transformation",
            "truth",
            "validation",
            "wind"
        ]
    },
    {
        "songName": "kabadi-song-lyrics.txt",
        "tags": [
            "celebration",
            "chanting",
            "culture",
            "energy",
            "excitement",
            "game",
            "language",
            "repetition",
            "transience"
        ]
    },
    {
        "songName": "kadhal-anukkal-song-lyrics.txt",
        "tags": [
            "Bluegrass",
            "Country",
            "Guitar",
            "Plucked string instrument",
            "Rock and roll",
            "Rock music",
            "butterflies",
            "mysticism",
            "poetic",
            "science",
            "surrealism"
        ]
    },
    {
        "songName": "kalyanamthan-kattikittu-song-lyrics.txt",
        "tags": [
            "Folk music",
            "Plucked string instrument",
            "cultural",
            "culture",
            "flirtatious",
            "humour",
            "language",
            "lighthearted",
            "love",
            "marriage",
            "playful",
            "romantic",
            "teasing",
            "traditions"
        ]
    },
    {
        "songName": "kandha-kaara-vadai-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "Rock music",
            "Ska",
            "competition",
            "corruption",
            "diversity",
            "inequality",
            "materialism"
        ]
    },
    {
        "songName": "kannal-pesum-pennae-song-lyrics.txt",
        "tags": [
            "Country",
            "Plucked string instrument",
            "apology",
            "beauty",
            "communication",
            "connection",
            "cultural",
            "culture",
            "emotion",
            "expression",
            "expressive",
            "eyes",
            "forgiveness",
            "knowledge",
            "language",
            "perception",
            "poetic",
            "poetry",
            "remorse",
            "request",
            "sensations",
            "sincerity",
            "transience",
            "understanding",
            "validation"
        ]
    },
    {
        "songName": "kannodu-kanbathellam-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Percussion",
            "cultural",
            "culture",
            "dance",
            "duality",
            "gentleness",
            "love",
            "metaphorical",
            "metaphysical",
            "oneness",
            "perception",
            "philosophical",
            "philosophy",
            "poetic",
            "poetry",
            "spiritual",
            "symbolic",
            "understanding",
            "unity"
        ]
    },
    {
        "songName": "kathal-website-ondru-song-lyrics.txt",
        "tags": [
            "acupuncture",
            "companion",
            "companionship",
            "computer",
            "confusion",
            "consent",
            "dolphin",
            "dress",
            "eyes",
            "fearlessness",
            "hardware",
            "hopelessness",
            "loneliness",
            "love",
            "permission",
            "poetic",
            "poetry",
            "prisoner",
            "sadness",
            "saxophone",
            "shakespeare",
            "software",
            "summer",
            "timelessness",
            "viral",
            "website",
            "winter"
        ]
    },
    {
        "songName": "kilimanjaro-song-lyrics.txt",
        "tags": [
            "Folk music",
            "admiration",
            "affection",
            "appreciation",
            "cultural",
            "culture",
            "exotic",
            "imagery",
            "language",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "poetic",
            "poetry",
            "romantic",
            "sensual",
            "sensuous",
            "symbolic",
            "wildlife"
        ]
    },
    {
        "songName": "kokkarakko-song-lyrics.txt",
        "tags": [
            "Guitar",
            "Plucked string instrument",
            "Tap",
            "affection",
            "anticipation",
            "appreciation",
            "cleansing",
            "contemplative",
            "encouragement",
            "faith",
            "gratitude",
            "happiness",
            "hope",
            "joy",
            "love",
            "mindfulness",
            "motivation",
            "nature",
            "positive",
            "positivity",
            "reflection",
            "relaxation",
            "validation"
        ]
    },
    {
        "songName": "kokku-para-para-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Percussion",
            "Plucked string instrument",
            "abstract",
            "contemplative",
            "creative",
            "creativity",
            "experimental",
            "imaginative",
            "introspective",
            "metaphor",
            "metaphorical",
            "metaphysical",
            "mystical",
            "philosophical",
            "philosophy",
            "playful",
            "poetic",
            "poetry",
            "reflective",
            "unconventional",
            "whimsical"
        ]
    },
    {
        "songName": "konja-neram-song-lyrics.txt",
        "tags": [
            "Classical music",
            "Orchestra",
            "contemplative",
            "creative",
            "deep",
            "dreamy",
            "enthusiastic",
            "imaginative",
            "introspective",
            "longing",
            "meditation",
            "melancholic",
            "metaphor",
            "metaphorical",
            "metaphysical",
            "mystical",
            "nostalgia",
            "passionate",
            "philosophical",
            "poetic",
            "poetry",
            "reflection",
            "reflective",
            "reverential",
            "romantic",
            "yearning"
        ]
    },
    {
        "songName": "Kuyilukku-koo-koo-koovida-song-lyrics.txt",
        "tags": [
            "celebration",
            "cultural",
            "culture",
            "enlightenment",
            "folklore",
            "happiness",
            "harmony",
            "hope",
            "joy",
            "love",
            "lyrical",
            "nature",
            "oneness",
            "prosperity",
            "romantic",
            "spiritual",
            "traditions",
            "transcendence",
            "transcendentalism",
            "unity"
        ]
    },
    {
        "songName": "ladio-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "attraction",
            "beauty",
            "chorus",
            "cultural",
            "culture",
            "empowerment",
            "fashion",
            "language",
            "metaphor",
            "metaphorical",
            "modelling",
            "repetition",
            "rhythmic",
            "seduction",
            "sensory"
        ]
    },
    {
        "songName": "magudi-magudi-songs-lyrics.txt",
        "tags": [
            "accountability",
            "affection",
            "anticipation",
            "celebration",
            "challenge",
            "culture",
            "destruction",
            "determination",
            "drums",
            "humour",
            "instruments",
            "motivation",
            "personification",
            "power",
            "pride",
            "rap",
            "reconciliation",
            "reflection",
            "rivalry",
            "separation",
            "traditions",
            "transformation",
            "validation",
            "victory"
        ]
    },
    {
        "songName": "manasellam-mazhaiye-song-lyrics.txt",
        "tags": [
            "beauty",
            "desire",
            "enchanting",
            "escapism",
            "ethereal",
            "fantasy",
            "imaginative",
            "inspiration",
            "longing",
            "love",
            "nature",
            "romantic",
            "whimsical",
            "yearning"
        ]
    },
    {
        "songName": "manjal-poosum-song-lyrics.txt",
        "tags": [
            "beauty",
            "flower",
            "imagery",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "poetic",
            "poetry",
            "romantic",
            "sky",
            "surrealism",
            "temple",
            "window"
        ]
    },
    {
        "songName": "maya-nadhi-lyrics.txt",
        "tags": [
            "Guitar",
            "Plucked string instrument",
            "anticipation",
            "contemplative",
            "despair",
            "healing",
            "hope",
            "hopelessness",
            "imagery",
            "introspective",
            "language",
            "longing",
            "love",
            "metaphorical",
            "nature",
            "pain",
            "poetic",
            "poetry",
            "rebirth",
            "reflection",
            "relationship",
            "separation",
            "surrender",
            "validation"
        ]
    },
    {
        "songName": "mei-nigara-song-lyrics.txt",
        "tags": [
            "Pig",
            "Pop music",
            "Rhythm and blues",
            "Soul music",
            "abstract",
            "confusion",
            "enigmatic",
            "experimental",
            "imagery",
            "infatuation",
            "intoxication",
            "irrational",
            "nonsensical",
            "personification",
            "poetic",
            "poetry",
            "separation",
            "transformation",
            "transience",
            "unconventional"
        ]
    },
    {
        "songName": ".merasalaayiten-song-lyrics.txt",
        "tags": [
            "abstract",
            "cultural",
            "culture",
            "enigmatic",
            "experimental",
            "imagery",
            "language",
            "lyrical",
            "nonsensical",
            "poetic",
            "poetry",
            "wordplay"
        ]
    },
    {
        "songName": "mississippi-song-lyrics.txt",
        "tags": [
            "cultural",
            "culture",
            "disjointed",
            "humorous",
            "irreverent",
            "lyrical",
            "nonsensical",
            "playful",
            "random"
        ]
    },
    {
        "songName": "moda-moda-song-lyrics.txt",
        "tags": [
            "absurd",
            "absurdity",
            "anger",
            "anticipation",
            "anxiety",
            "confusion",
            "contentment",
            "cultural",
            "culture",
            "desperation",
            "frustration",
            "hopelessness",
            "humour",
            "infatuation",
            "language",
            "madness",
            "motivation",
            "nonsense",
            "surrealism",
            "wordplay"
        ]
    },
    {
        "songName": "moongil-thottam-song-lyrics.txt",
        "tags": [
            "appreciation",
            "companionship",
            "contentment",
            "silence",
            "simplicity",
            "smell"
        ]
    },
    {
        "songName": "motta-paiyan-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "attraction",
            "beauty",
            "desire",
            "desperation",
            "devotion",
            "enthusiastic",
            "euphoria",
            "frustration",
            "infatuation",
            "intense",
            "love",
            "obsession",
            "passionate",
            "personification",
            "poetic",
            "poetry",
            "romantic",
            "sensual",
            "sensuous",
            "yearning"
        ]
    },
    {
        "songName": "mouname-unnidam-song-lyrics.txt",
        "tags": [
            "anticipation",
            "beauty",
            "communication",
            "connection",
            "contemplative",
            "determination",
            "expression",
            "expressive",
            "introspective",
            "language",
            "meaning",
            "meditation",
            "personification",
            "reconciliation",
            "reflection",
            "separation",
            "silence",
            "transformation",
            "transience",
            "validation",
            "womanhood"
        ]
    },
    {
        "songName": "my-name-is-billa-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Rock and roll",
            "Rock music",
            "Strum",
            "ambiguity",
            "individualism",
            "introspective",
            "morality",
            "reflection",
            "relationship",
            "uncertainty"
        ]
    },
    {
        "songName": "my-twin-brother-song-lyrics.txt",
        "tags": [
            "Explosion",
            "Fusillade",
            "Gunshot, gunfire",
            "Outside, rural or natural",
            "Smash, crash"
        ]
    },
    {
        "songName": "naan-meendum-song-lyrics.txt",
        "tags": [
            "ambiguity",
            "anticipation",
            "communication",
            "contemplative",
            "creation",
            "desire",
            "determination",
            "duality",
            "existential",
            "identity",
            "illusion",
            "individualism",
            "innovation",
            "introspective",
            "materialism",
            "mobilisation",
            "morality",
            "motivation",
            "mysticism",
            "personification",
            "reality",
            "reflection",
            "separation",
            "surrender",
            "transcendence",
            "transcendentalism",
            "transformation",
            "transience",
            "truth",
            "validation"
        ]
    },
    {
        "songName": "naan-sirithal-deepavali-song-lyrics.txt",
        "tags": [
            "anticipation",
            "beauty",
            "celebration",
            "contemplative",
            "cultural",
            "culture",
            "detachment",
            "determination",
            "fearlessness",
            "festival",
            "hopelessness",
            "impermanence",
            "introspective",
            "joy",
            "loneliness",
            "metaphorical",
            "metaphysical",
            "mystical",
            "personification",
            "poetic",
            "poetry",
            "reflection",
            "selflessness",
            "spiritual",
            "supernatural",
            "timelessness",
            "transcendence",
            "validation"
        ]
    },
    {
        "songName": "naan-un-azhaginilae-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Country",
            "Guitar",
            "Harp",
            "Plucked string instrument",
            "Violin, fiddle",
            "admiration",
            "affection",
            "appreciation",
            "beauty",
            "divine",
            "enchanting",
            "encouragement",
            "ethereal",
            "love",
            "mesmerising",
            "metaphysical",
            "motivation",
            "poetic",
            "poetry",
            "romantic",
            "soulful",
            "spiritual",
            "transcendence",
            "transcendentalism",
            "worship"
        ]
    },
    {
        "songName": "naani-koni-song-lyrics.txt",
        "tags": [
            "Clip-clop",
            "Country",
            "Plucked string instrument",
            "Rock and roll",
            "Run",
            "Sound effect",
            "beauty",
            "devotion",
            "emotion",
            "language",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "poetic",
            "poetry",
            "romantic",
            "sensations",
            "yearning"
        ]
    },
    {
        "songName": "nahna-na-nah-song-lyrics.txt",
        "tags": [
            "Chant",
            "Mantra",
            "Middle Eastern music",
            "celebration",
            "dance",
            "empowerment",
            "party",
            "sensual"
        ]
    },
    {
        "songName": "nalla-nanban-song-lyrics.txt",
        "tags": [
            "anticipation",
            "burden",
            "companion",
            "companionship",
            "death",
            "desperation",
            "emotion",
            "faith",
            "friendship",
            "frustration",
            "grief",
            "infatuation",
            "loss",
            "memory",
            "mercy",
            "plea",
            "questioning",
            "sorrow",
            "sorrowful",
            "support"
        ]
    },
    {
        "songName": "nee-illai-endraal-song-lyrics.txt",
        "tags": [
            "city",
            "desire",
            "dress",
            "fate",
            "love",
            "night",
            "painting",
            "rainbow",
            "sculpture",
            "silence",
            "sword"
        ]
    },
    {
        "songName": "nee-oru-kadhal-sangeetham-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Drum",
            "Folk music",
            "Tabla",
            "beauty",
            "divine",
            "enlightenment",
            "expression",
            "expressive",
            "journey",
            "joy",
            "love",
            "lyricism",
            "nature",
            "oneness",
            "poetic",
            "poetry",
            "rain",
            "romantic",
            "spiritual",
            "transcendence",
            "transcendentalism",
            "transience",
            "unity"
        ]
    },
    {
        "songName": "nenje-nenje-song-lyrics-2.txt",
        "tags": [
            "Bowed string instrument",
            "Country",
            "Guitar",
            "Mandolin",
            "Pizzicato",
            "Plucked string instrument",
            "Steelpan",
            "anticipation",
            "creation",
            "desperation",
            "determination",
            "dissolution",
            "emotion",
            "existential",
            "frustration",
            "hope",
            "impossibility",
            "inevitability",
            "infatuation",
            "longing",
            "love",
            "lyrical",
            "melancholic",
            "metaphorical",
            "metaphysical",
            "personification",
            "philosophical",
            "philosophy",
            "poetic",
            "poetry",
            "questioning",
            "reconciliation",
            "romantic",
            "separation",
            "spiritual",
            "transformation",
            "validation",
            "yearning"
        ]
    },
    {
        "songName": "nenjukulle-song-lyrics-2.txt",
        "tags": [
            "Bowed string instrument",
            "Guitar",
            "Plucked string instrument",
            "Tender music",
            "Violin, fiddle",
            "anticipation",
            "creation",
            "determination",
            "fearlessness",
            "hopelessness",
            "loneliness",
            "mobilisation",
            "nostalgia",
            "personification",
            "selflessness",
            "separation",
            "timelessness",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "nerrupu-da-nerunghu-da-lyrics.txt",
        "tags": [
            "Explosion",
            "Gunshot, gunfire",
            "Outside, rural or natural",
            "Rock music",
            "Smash, crash",
            "determined",
            "hopeful",
            "resilience",
            "sacrifice"
        ]
    },
    {
        "songName": "nila-adhu-vanathumele-song-lyrics.txt",
        "tags": [
            "ally",
            "companion",
            "companionship",
            "cruelty",
            "dance",
            "dancing",
            "fox",
            "hunger",
            "poverty",
            "proletariat",
            "screen",
            "sky",
            "tooth"
        ]
    },
    {
        "songName": "oh-super-nova-song-lyrics.txt",
        "tags": [
            "adventure",
            "celebration",
            "energetic",
            "enthusiastic",
            "joyful",
            "joyous",
            "lyricism",
            "passionate",
            "patriotic",
            "pop",
            "travel",
            "unity",
            "upbeat",
            "wanderlust"
        ]
    },
    {
        "songName": "oru-maalai-song-lyrics.txt",
        "tags": [
            "beauty",
            "change",
            "contemplative",
            "determination",
            "food",
            "habit",
            "lightning",
            "obsession",
            "perception",
            "personification",
            "power",
            "reflection",
            "reflective",
            "romantic",
            "smile",
            "springtime",
            "transformation",
            "truth",
            "yearning"
        ]
    },
    {
        "songName": "oyaayiye-yaayiye-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "beauty",
            "desperation",
            "euphoria",
            "frustration",
            "imagery",
            "infatuation",
            "longing",
            "love",
            "nature",
            "obsession",
            "personification",
            "poetic",
            "poetry",
            "romantic",
            "sensory",
            "yearning"
        ]
    },
    {
        "songName": "pala-palakura-song-lyrics.txt",
        "tags": [
            "Clip-clop",
            "Flamenco",
            "Music of Latin America",
            "Run",
            "Tap",
            "beauty",
            "creative",
            "creativity",
            "excitement",
            "freedom",
            "happiness",
            "hope",
            "joy",
            "love",
            "nature",
            "nostalgia",
            "rain",
            "youth"
        ]
    },
    {
        "songName": "pengaloda-potti-podum-song-lyrics.txt",
        "tags": [
            "competition",
            "femininity",
            "language",
            "masculinity",
            "mysticism",
            "relationship",
            "surrealism",
            "values"
        ]
    },
    {
        "songName": "pesa-madandhaiye-song-lyrics.txt",
        "tags": [
            "anger",
            "beauty",
            "confusion",
            "emotion",
            "heartbreak",
            "language",
            "loss",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "poetic",
            "poetry",
            "relationship",
            "sacrifice",
            "sensations",
            "symbolic"
        ]
    },
    {
        "songName": "pom-pom-penne-song-lyrics.txt",
        "tags": [
            "anger",
            "bitterness",
            "confrontation",
            "determination",
            "forgiveness",
            "hope",
            "longing",
            "love",
            "nostalgia",
            "reconciliation",
            "redemption",
            "regret",
            "relationship",
            "separation",
            "sweetness",
            "unity"
        ]
    },
    {
        "songName": "pookalae-sattru-oyivedungal-song-lyrics.txt",
        "tags": [
            "blessing",
            "creation",
            "positive",
            "spiritual",
            "surrender",
            "transformation"
        ]
    },
    {
        "songName": "poongatre-poongatre-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "anticipation",
            "appreciation",
            "beauty",
            "contemplative",
            "determination",
            "encouragement",
            "fleeting",
            "happiness",
            "imagery",
            "introspective",
            "longing",
            "love",
            "memory",
            "motivation",
            "nature",
            "nostalgia",
            "personification",
            "poetic",
            "poetry",
            "reflection",
            "romantic",
            "validation"
        ]
    },
    {
        "songName": "poonkatrae-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Cello",
            "Orchestra",
            "String section",
            "Violin, fiddle",
            "change",
            "heart",
            "justice",
            "nature",
            "pain",
            "struggle",
            "time",
            "truth",
            "witness"
        ]
    },
    {
        "songName": "thirunelveli-halwada-song-lyrics.txt",
        "tags": [
            "Drum",
            "Jazz",
            "Percussion",
            "Rock and roll",
            "Rock music",
            "celebration",
            "dance"
        ]
    },
    {
        "songName": "poovukkul-olinthirukkum-song-lyrics.txt",
        "tags": [
            "Country",
            "Flute",
            "Wind instrument, woodwind instrument",
            "amazement",
            "beauty",
            "butterflies",
            "butterfly",
            "cheek",
            "creative",
            "creativity",
            "crown",
            "curve",
            "eyes",
            "finger",
            "flower",
            "love",
            "miracles",
            "nature",
            "sky",
            "wonder"
        ]
    },
    {
        "songName": "pudhiya-manidha-song-lyrics.txt",
        "tags": [
            "Electronic music",
            "Percussion",
            "admiration",
            "creation",
            "determination",
            "empowerment",
            "futuristic",
            "hope",
            "innovation",
            "life",
            "miracles",
            "optimism",
            "personification",
            "technology",
            "transformation",
            "transience",
            "wonder"
        ]
    },
    {
        "songName": "pudichirukku-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "communication",
            "creation",
            "desire",
            "desperation",
            "determination",
            "devotion",
            "frustration",
            "gentleness",
            "infatuation",
            "innocence",
            "innovation",
            "love",
            "mobilisation",
            "motivation",
            "obsession",
            "personification",
            "playfulness",
            "reflection",
            "romantic",
            "seduction",
            "separation",
            "surrender",
            "temptation",
            "transformation",
            "transience",
            "validation"
        ]
    },
    {
        "songName": "punnagaye-pala-pala-palavena.txt",
        "tags": [
            "Mallet percussion",
            "Marimba, xylophone",
            "Percussion",
            "Plucked string instrument",
            "Rock and roll",
            "Vibraphone",
            "beauty",
            "celebration",
            "communication",
            "connection",
            "gratitude",
            "joy",
            "nature",
            "positive",
            "positivity",
            "rain"
        ]
    },
    {
        "songName": "ragasiyam-ondru-song-lyrics.txt",
        "tags": [
            "loneliness",
            "love",
            "mysticism",
            "nostalgia",
            "pain",
            "surrealism",
            "timelessness",
            "yearning"
        ]
    },
    {
        "songName": "rahathulla-rahathulla-song-lyrics.txt",
        "tags": [
            "beauty",
            "change",
            "cultural",
            "culture",
            "desire",
            "diversity",
            "fleeting",
            "gamble",
            "hopefulness",
            "nature",
            "nostalgia",
            "poetic",
            "poetry",
            "uncertainty",
            "yearning"
        ]
    },
    {
        "songName": "rangola-hola-hola-song-lyrics.txt",
        "tags": [
            "affection",
            "desperation",
            "energetic",
            "frustration",
            "infatuation",
            "language",
            "love",
            "personification",
            "playful",
            "romantic",
            "seduction",
            "sensual",
            "sensuous",
            "upbeat",
            "youthful"
        ]
    },
    {
        "songName": "rathiri-nerathu-poojayil-song-lyrics.txt",
        "tags": [
            "Drum",
            "Guitar",
            "Middle Eastern music",
            "Percussion",
            "Plucked string instrument",
            "Yodeling",
            "redemption",
            "river"
        ]
    },
    {
        "songName": "rettai-kathire-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Cello",
            "contemplative",
            "creation",
            "determination",
            "emotion",
            "enlightenment",
            "faith",
            "introspective",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "motivation",
            "nature",
            "oneness",
            "poetic",
            "poetry",
            "reflection",
            "sensations",
            "separation",
            "spiritual",
            "symbolic",
            "transformation",
            "unity",
            "validation"
        ]
    },
    {
        "songName": "royapuram-peter-song-lyrics.txt",
        "tags": [
            "Outside, urban or manmade",
            "Rock and roll",
            "Rock music",
            "bravado",
            "celebration",
            "colloquial",
            "culture",
            "dance",
            "dancing",
            "energetic",
            "friendship",
            "fun",
            "language",
            "love",
            "pride",
            "youth"
        ]
    },
    {
        "songName": "rukku-rukku-roop-kya-song-lyrics.txt",
        "tags": [
            "celebration",
            "cloud",
            "colour",
            "disco",
            "fashion",
            "game",
            "heart",
            "laughter",
            "lightning",
            "melting",
            "memories",
            "sweetness",
            "thought",
            "youth"
        ]
    },
    {
        "songName": "sandi-muni-song-lyrics.txt",
        "tags": [
            "Explosion",
            "Gunshot, gunfire",
            "Percussion",
            "Smash, crash",
            "Whack, thwack",
            "aggression",
            "chanting",
            "culture",
            "dance",
            "mantra",
            "mystical",
            "mysticism",
            "mythology",
            "performance",
            "power",
            "revenge",
            "spiritual",
            "supernatural",
            "suppression",
            "tantra",
            "transcendentalism",
            "violence"
        ]
    },
    {
        "songName": "sangeetha-jaathi-mullai-song-lyrics.txt",
        "tags": [
            "Classical music",
            "Tabla",
            "beauty",
            "longing",
            "love",
            "melody",
            "memory",
            "nature",
            "peacock",
            "poetic",
            "poetry",
            "rhythmic",
            "sorrow",
            "sorrowful",
            "vocals"
        ]
    },
    {
        "songName": "sei-yedhavathu-sei-song-lyrics.txt",
        "tags": [
            "danger",
            "death",
            "desire",
            "empowerment",
            "enlightenment",
            "love",
            "mysticism",
            "obsession",
            "oneness",
            "rebellion",
            "sacrifice",
            "seduction",
            "spiritual",
            "temptation",
            "transcendence",
            "transcendentalism"
        ]
    },
    {
        "songName": "seval-kodi-song-lyrics.txt",
        "tags": [
            "culture",
            "dance",
            "language",
            "leadership",
            "patriotic",
            "protection",
            "struggle",
            "unity",
            "valour",
            "worship"
        ]
    },
    {
        "songName": "sevvanam-selai-katti-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "beauty",
            "culture",
            "desperation",
            "electricity",
            "fire",
            "frustration",
            "infatuation",
            "lightning",
            "longing",
            "love",
            "obsession",
            "personification",
            "poetic",
            "poetry",
            "romantic"
        ]
    },
    {
        "songName": "sha-la-la-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Folk music",
            "Guitar",
            "Harpsichord",
            "Plucked string instrument",
            "desire",
            "dreamy",
            "emotion",
            "hope",
            "longing",
            "memories",
            "nature",
            "nostalgia",
            "past",
            "whimsical"
        ]
    },
    {
        "songName": "silatta-pilatta-song-lyrics.txt",
        "tags": [
            "Smash, crash",
            "anticipation",
            "confusion",
            "desperation",
            "infatuation",
            "mobilisation",
            "supernatural",
            "tension"
        ]
    },
    {
        "songName": "singalathu-chinnakuyile-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Folk music",
            "Middle Eastern music",
            "Plucked string instrument",
            "admiration",
            "affection",
            "appreciation",
            "cultural",
            "culture",
            "love",
            "lyrical",
            "mantra",
            "nature",
            "peacock",
            "poetic",
            "poetry",
            "queen",
            "rhythmic",
            "romantic",
            "sentimental",
            "traditions"
        ]
    },
    {
        "songName": "sollamal-thottu-chellum-thendral-song-lyrics.txt",
        "tags": [
            "fearlessness",
            "hopelessness",
            "loneliness",
            "love",
            "selflessness",
            "sensations",
            "timelessness"
        ]
    },
    {
        "songName": "soora-thenga-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Rock and roll",
            "Strum",
            "appreciation",
            "beauty",
            "celebration",
            "cultural",
            "culture",
            "dance",
            "dancing",
            "deities",
            "encouragement",
            "fun",
            "life",
            "motivation",
            "traditions"
        ]
    },
    {
        "songName": "suthuthe-suthuthe-bhoomi-song-lyrics.txt",
        "tags": [
            "Tender music",
            "admiration",
            "affection",
            "appreciation",
            "beauty",
            "longing",
            "love",
            "memory",
            "nostalgia",
            "romance",
            "spring",
            "yearning"
        ]
    },
    {
        "songName": "sutrum-vizhi-sudarae-song-lyrics.txt",
        "tags": [
            "Percussion",
            "Plucked string instrument",
            "Trumpet",
            "affection",
            "ballad",
            "desperation",
            "devotion",
            "frustration",
            "imagery",
            "infatuation",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "obsession",
            "personification",
            "romantic"
        ]
    },
    {
        "songName": "thangamey-onnathaan-song-lyrics.txt",
        "tags": [
            "Country",
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Rock and roll",
            "Rock music",
            "Strum",
            "anticipation",
            "confidence",
            "desperation",
            "determination",
            "devotion",
            "infatuation",
            "kidnapping",
            "mobilisation",
            "persistence",
            "personification",
            "separation",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "thani-oruvan-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Cello",
            "Orchestra",
            "Rock and roll",
            "Rock music",
            "String section",
            "accountability",
            "anticipation",
            "bravery",
            "cultural",
            "culture",
            "determination",
            "fearlessness",
            "gangsters",
            "heroism",
            "individualism",
            "leadership",
            "loneliness",
            "materialism",
            "motivation",
            "power",
            "rap",
            "rebellion",
            "reflection",
            "selflessness",
            "strength",
            "transcendentalism",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "thedum-kan-paarvai-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Drum",
            "Folk music",
            "Percussion",
            "Tabla",
            "creation",
            "desire",
            "determination",
            "dissolution",
            "fleeting",
            "hope",
            "impermanence",
            "longing",
            "love",
            "poetic",
            "poetry",
            "reconciliation",
            "romance",
            "search",
            "separation",
            "transcendence",
            "transformation",
            "uncertainty",
            "validation"
        ]
    },
    {
        "songName": "thee-illai-song-lyrics.txt",
        "tags": [
            "anticipation",
            "contemplative",
            "desire",
            "determination",
            "devotion",
            "imagery",
            "introspective",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "mysticism",
            "nature",
            "personification",
            "poetic",
            "poetry",
            "reflection",
            "romantic",
            "sacrifice",
            "sensory",
            "surrender",
            "symbolic",
            "validation",
            "yearning"
        ]
    },
    {
        "songName": "theemai-thaan-vellum-song-lyrics.txt",
        "tags": [
            "Orchestra",
            "Percussion",
            "Rock and roll",
            "Rock music",
            "accountability",
            "cannibalism",
            "conflict",
            "conquest",
            "control",
            "corruption",
            "darkness",
            "deception",
            "existential",
            "fear",
            "greed",
            "impossibility",
            "inevitability",
            "morality",
            "power",
            "rap",
            "superiority",
            "truth",
            "vulnerability"
        ]
    },
    {
        "songName": "theeye-theeye-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "beauty",
            "dance",
            "dancing",
            "desire",
            "duality",
            "fire",
            "intimacy",
            "love",
            "nature",
            "poetic",
            "poetry",
            "romance",
            "seduction",
            "temptation",
            "youth"
        ]
    },
    {
        "songName": "thendral-varum-song-lyrics.txt",
        "tags": [
            "beauty",
            "breeze",
            "creation",
            "determination",
            "dissolution",
            "flower",
            "longing",
            "love",
            "melancholic",
            "nature",
            "nostalgia",
            "pain",
            "personification",
            "poetic",
            "poetry",
            "reconciliation",
            "romantic",
            "separation",
            "transformation",
            "validation",
            "yearning"
        ]
    },
    {
        "songName": "thenpandi-cheemayile-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "chariot",
            "confusion",
            "contemplative",
            "emotion",
            "introspective",
            "loneliness",
            "loss",
            "mystery",
            "questioning",
            "reflection",
            "sadness",
            "street"
        ]
    },
    {
        "songName": "tholvi-nilayena-ninaithaal-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Chant",
            "Classical music",
            "Mantra",
            "Middle Eastern music",
            "Orchestra",
            "Yodeling",
            "bloodshed",
            "bravery",
            "despair",
            "emotion",
            "failure",
            "fear",
            "fearlessness",
            "heroism",
            "hopelessness",
            "loneliness",
            "loss",
            "madness",
            "possessions",
            "rights",
            "selflessness",
            "sensations",
            "senses",
            "timelessness",
            "war"
        ]
    },
    {
        "songName": "thooliyile-aadavantha-song-lyrics.txt",
        "tags": [
            "Folk music",
            "Guitar",
            "Plucked string instrument",
            "childhood",
            "cultural",
            "culture",
            "folk",
            "gratitude",
            "language",
            "longing",
            "memories",
            "motherhood",
            "nostalgia",
            "pain",
            "poetic",
            "poetry",
            "rural",
            "sacrifice",
            "traditions",
            "values"
        ]
    },
    {
        "songName": "thuli-thuli-thuli-mazhaiyaai-song-lyrics.txt",
        "tags": [
            "admiration",
            "affection",
            "appreciation",
            "beauty",
            "desire",
            "desperation",
            "devotion",
            "frustration",
            "imagery",
            "infatuation",
            "longing",
            "love",
            "metaphor",
            "metaphorical",
            "nature",
            "personification",
            "pursuit",
            "romantic",
            "surrender",
            "yearning"
        ]
    },
    {
        "songName": "ulagam-oruvanukka-song-lyrics.txt",
        "tags": [
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "accountability",
            "affection",
            "aggression",
            "anticipation",
            "determination",
            "humility",
            "identity",
            "leadership",
            "loyalty",
            "motivation",
            "perseverance",
            "persistence",
            "personification",
            "power",
            "rebellion",
            "reconciliation",
            "reflection",
            "sacrifice",
            "separation",
            "struggle",
            "suppression",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "un-paarvayil-song-lyrics.txt",
        "tags": [
            "accountability",
            "admiration",
            "affection",
            "appreciation",
            "contentment",
            "creation",
            "desire",
            "desperation",
            "determination",
            "devotion",
            "enchantment",
            "frustration",
            "happiness",
            "infatuation",
            "intimacy",
            "joy",
            "love",
            "obsession",
            "personification",
            "romantic"
        ]
    },
    {
        "songName": "un-vizhigalil-vizhuntha-song-lyrics.txt",
        "tags": [
            "Bowed string instrument",
            "Electric guitar",
            "Guitar",
            "Plucked string instrument",
            "Violin, fiddle",
            "accountability",
            "admiration",
            "affection",
            "appreciation",
            "commitment",
            "contentment",
            "creation",
            "desire",
            "desperation",
            "devotion",
            "encouragement",
            "frustration",
            "fulfilment",
            "happiness",
            "infatuation",
            "love",
            "motivation",
            "obsession",
            "personification",
            "romantic",
            "surrender",
            "yearning"
        ]
    },
    {
        "songName": "vaa-vennila-song-lyrics.txt",
        "tags": [
            "Carnatic music",
            "Drum",
            "Folk music",
            "Middle Eastern music",
            "Percussion",
            "Tabla",
            "anticipation",
            "creation",
            "desperation",
            "determination",
            "devotion",
            "infatuation",
            "mobilisation",
            "nostalgia",
            "personification",
            "sacrifice",
            "sentimental",
            "separation",
            "transformation",
            "validation",
            "yearning"
        ]
    },
    {
        "songName": "vaan-megam-poo-poovaai-song-lyrics.txt",
        "tags": [
            "celebration",
            "movement",
            "playfulness"
        ]
    },
    {
        "songName": "vaanam-paarthen-lyrics.txt",
        "tags": [
            "anticipation",
            "creation",
            "deception",
            "determination",
            "fearlessness",
            "hopelessness",
            "loneliness",
            "mobilisation",
            "nostalgia",
            "personification",
            "selflessness",
            "separation",
            "timelessness",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "vaanam-perusuthan-song-lyrics.txt",
        "tags": [
            "Rock and roll",
            "celebration",
            "cultural",
            "friendship",
            "idealistic",
            "inspiring",
            "joyful",
            "joyous",
            "optimistic",
            "playful",
            "poetic",
            "poetry",
            "romantic",
            "sentimental"
        ]
    },
    {
        "songName": "vaaraayo-thozhi-song-lyrics.txt",
        "tags": [
            "celebration",
            "cultural",
            "culture",
            "friendship",
            "fun",
            "joyful",
            "joyous",
            "memories",
            "nostalgia",
            "playful"
        ]
    },
    {
        "songName": "vaarai-naan-unnai-thedi-song-lyrics.txt",
        "tags": [
            "celebration",
            "dance",
            "dancing",
            "desire",
            "devotion",
            "flower",
            "honey",
            "leader",
            "love",
            "poetic",
            "poetry",
            "romantic",
            "seasons",
            "virility",
            "yearning"
        ]
    },
    {
        "songName": "vaaya-en-veera-song-lyrics.txt",
        "tags": [
            "Flamenco",
            "Keyboard (musical)",
            "Piano",
            "connection",
            "desire",
            "devotion",
            "emotion",
            "hope",
            "longing",
            "loss",
            "love",
            "motivation",
            "nature",
            "nostalgia",
            "pain",
            "reunion",
            "romance",
            "seasons",
            "separation",
            "transience",
            "yearning"
        ]
    },
    {
        "songName": "varavaa-varavaa-song-lyrics.txt",
        "tags": [
            "accountability",
            "affection",
            "anticipation",
            "challenge",
            "commitment",
            "confrontation",
            "consequences",
            "contentment",
            "defiance",
            "determination",
            "empowerment",
            "inevitability",
            "justice",
            "motivation",
            "perseverance",
            "persistence",
            "personification",
            "reconciliation",
            "redemption",
            "reflection",
            "regret",
            "revenge",
            "separation",
            "strength",
            "transformation",
            "transience",
            "validation",
            "warning"
        ]
    },
    {
        "songName": "vasamilla-malar-idhu-song-lyrics.txt",
        "tags": [
            "cultural",
            "culture",
            "deception",
            "desire",
            "flower",
            "instruments",
            "longing",
            "love",
            "mythology",
            "nature",
            "poetic",
            "poetry",
            "spring",
            "symbolic"
        ]
    },
    {
        "songName": "vathikuchi-pathikadhuda-song-lyrics.txt",
        "tags": [
            "Accordion",
            "Jazz",
            "accountability",
            "affection",
            "anticipation",
            "appreciation",
            "determination",
            "empowerment",
            "encouragement",
            "hope",
            "humility",
            "inspiration",
            "motivation",
            "optimism",
            "perseverance",
            "persistence",
            "personification",
            "positive",
            "positivity",
            "reconciliation",
            "reflection",
            "resilience",
            "separation",
            "strength",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "veera-thurandhara-song-lyrics.txt",
        "tags": [
            "accountability",
            "affection",
            "anticipation",
            "courage",
            "determination",
            "empowerment",
            "freedom",
            "gangsters",
            "humility",
            "inspiration",
            "leadership",
            "loyalty",
            "motivation",
            "perseverance",
            "persistence",
            "personification",
            "pride",
            "reconciliation",
            "reflection",
            "revolution",
            "righteousness",
            "separation",
            "struggle",
            "transformation",
            "validation",
            "victory"
        ]
    },
    {
        "songName": "velicha-poovae-song-lyrics.txt",
        "tags": [
            "electricity",
            "flower",
            "haiku",
            "love",
            "peacock",
            "rain",
            "sun",
            "tingling",
            "touch",
            "yearning",
            "youth"
        ]
    },
    {
        "songName": "vella-bambaram-song-lyrics.txt",
        "tags": [
            "cultural",
            "culture",
            "family",
            "gentleness",
            "humour",
            "infatuation",
            "longing",
            "love",
            "marriage",
            "nostalgia",
            "playfulness",
            "relationship",
            "seduction",
            "traditions",
            "wordplay"
        ]
    },
    {
        "songName": "velli-salangaigal-song-lyrics.txt",
        "tags": [
            "beauty",
            "celebration",
            "dance",
            "dancing",
            "devotion",
            "emotion",
            "goddess",
            "harmony",
            "joy",
            "love",
            "mythology",
            "poetic",
            "poetry",
            "sensations",
            "spiritual",
            "temple",
            "traditions"
        ]
    },
    {
        "songName": "venam-machan-venam-song-lyrics.txt",
        "tags": [
            "Folk music",
            "Middle Eastern music",
            "beach",
            "friendship",
            "heartbreak",
            "longing",
            "memories",
            "nostalgia",
            "pain",
            "poster",
            "romance",
            "sea",
            "tears",
            "trust",
            "youth"
        ]
    },
    {
        "songName": "veppamaram-song-lyrics.txt",
        "tags": [
            "countryside",
            "cultural",
            "culture",
            "identity",
            "life",
            "longing",
            "nature",
            "nostalgia",
            "poverty",
            "trees"
        ]
    },
    {
        "songName": "vethalaiya-potendi-song-lyrics.txt",
        "tags": [
            "aggression",
            "ascent",
            "blood",
            "change",
            "energy",
            "explosion",
            "foot",
            "hammer",
            "heart",
            "hopelessness",
            "intellect",
            "madness",
            "power",
            "sparrow",
            "suppression",
            "tiger",
            "trap",
            "umbrella",
            "wet"
        ]
    },
    {
        "songName": "vizhi-moodi-yosithal-song-lyrics.txt",
        "tags": [
            "Clip-clop",
            "anticipation",
            "attraction",
            "contemplative",
            "contentment",
            "creation",
            "desire",
            "determination",
            "enlightenment",
            "imaginative",
            "infatuation",
            "inspiration",
            "introspective",
            "longing",
            "love",
            "magic",
            "meditation",
            "motivation",
            "nature",
            "nostalgia",
            "personification",
            "rain",
            "reconciliation",
            "reflection",
            "separation",
            "solitude",
            "transcendence",
            "transformation",
            "transience",
            "validation"
        ]
    },
    {
        "songName": "x-machi-y-machi-song-lyrics.txt",
        "tags": [
            "contemplative",
            "dreamy",
            "energetic",
            "enthusiastic",
            "flirtatious",
            "hopeful",
            "introspective",
            "lively",
            "love",
            "melancholic",
            "nature",
            "passionate",
            "radio",
            "reflective",
            "romantic",
            "solitude"
        ]
    },
    {
        "songName": "yaarume-kekkave-illa-song-lyrics.txt",
        "tags": [
            "anger",
            "betrayal",
            "cheating",
            "confusion",
            "deception",
            "denial",
            "desire",
            "humour",
            "loneliness",
            "love",
            "pleading",
            "relationship",
            "sadness",
            "trust",
            "warning"
        ]
    },
    {
        "songName": "yedhedho-ennam-valarthen-song-lyrics.txt",
        "tags": [
            "acceptance",
            "devotion",
            "enlightenment",
            "faith",
            "fearlessness",
            "gratitude",
            "hopelessness",
            "humility",
            "longing",
            "love",
            "oneness",
            "peace",
            "prayer",
            "selflessness",
            "spiritual",
            "surrender",
            "timelessness",
            "transcendence",
            "transcendentalism",
            "trust",
            "worship"
        ]
    },
    {
        "songName": "yedho-ondru-song-lyrics.txt",
        "tags": [
            "anticipation",
            "creation",
            "determination",
            "melancholic",
            "mobilisation",
            "personification",
            "sensations",
            "separation",
            "transformation",
            "validation"
        ]
    },
    {
        "songName": "yeh-nanbane-kobam-song-lyrics.txt",
        "tags": [
            "anger",
            "appreciation",
            "electricity",
            "encouragement",
            "fantasy",
            "fire",
            "friendship",
            "love",
            "marriage",
            "mistakes",
            "motivation",
            "optimism",
            "pain",
            "pride",
            "relationship",
            "wings",
            "youth"
        ]
    },
    {
        "songName": "yethi-yethi-song-lyrics.txt",
        "tags": [
            "aggression",
            "bravado",
            "challenge",
            "culture",
            "dominance",
            "gangsters",
            "pride",
            "rebellion",
            "sarcasm",
            "suppression",
            "warning"
        ]
    }
]